# Generated by Django 6.0.8 on 2026-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_qr_codes/'),
        ),
    ]
